version: "3"

services:
  ingress:
    build: .
    command: "python ingress.py"
    volumes:
      - ".:/app"
    depends_on:
      - rabbit
      - redis

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:5.0-rc-alpine

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres