version: "3"

services:
  parser:
    build: .
    command: "python -m celery worker -A app -Q parse_killmail -c 40"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
      - rabbit
      - redis

  hydrate:
    build: .
    command: "python -m celery worker -A app -Q hydrate_character,hydrate_corporation,hydrate_alliance -c 32"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
      - rabbit
      - redis


  backend_api:
    build: .
    command: "gunicorn backend:app -w 4 -b 0.0.0.0:80"
    ports:
      - "6767:80"
    volumes:
      - ".:/app"
    depends_on:
      - postgres


  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  redis:
    image: redis:5.0-rc
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  flower:
    build: .
    command: python -m flower -A app --port=5555 --address=0.0.0.0
    ports:
      - "5555:5555"
    depends_on:
      - parser
      - hydrate


volumes:
  pg_data:
  redis_data:
  rabbit_data:
