version: "3"

services:
  parser:
    build: .
    command: "python -m celery worker -A app -Q parse_killmail -c 2"
    volumes:
      - ".:/app"
    depends_on:
      - rabbit
      - redis

  hydrate:
    build: .
    command: "python -m celery worker -A app -Q hydrate_character,hydrate_corporation,hydrate_alliance -c 64"
    volumes:
      - ".:/app"
    depends_on:
      - rabbit
      - redis

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:5.0-rc-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres