# Generated by Django 2.1.1 on 2018-09-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alliance',
            table='alliance',
        ),
        migrations.AlterModelTable(
            name='character',
            table='character',
        ),
        migrations.AlterModelTable(
            name='corporation',
            table='corporation',
        ),
        migrations.AlterModelTable(
            name='involved',
            table='involved',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='killmail',
            table='killmail',
        ),
    ]
