# Generated by Django 2.1.1 on 2018-10-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180930_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involved',
            name='ship_type',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved_ships', to='sde.Type'),
        ),
        migrations.AlterField(
            model_name='involved',
            name='weapon_type',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved_weapons', to='sde.Type'),
        ),
    ]
