# Generated by Django 2.1.1 on 2018-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181001_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='security_status',
            field=models.FloatField(default=0),
        ),
    ]
