# Generated by Django 2.1.1 on 2018-10-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_character_security_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='corporation',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Corporation'),
        ),
    ]
