# Generated by Django 2.1.1 on 2018-10-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181001_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='alliance',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Alliance'),
        ),
    ]
