# Generated by Django 2.1.1 on 2018-10-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181002_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='killmail',
            name='involved_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='killmail',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=16),
        ),
    ]
