# Generated by Django 2.1.1 on 2018-10-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181006_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involved',
            name='weapon_type',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved_weapons', to='sde.Type'),
        ),
    ]
